### ISSUE TITLE
Both horizontal and vertical scroll bars are being undesirably shown.

### ISSUE THREAD

**Issue by SudhanshuBhogal** [Colt/react-colors#6]
Both horizontal and vertical scroll bars are being shown after running the code in this commit which are not there in the course's videos

![Screenshot (28)_LI](https://user-images.githubusercontent.com/47147531/77162329-bc6a1780-6ad1-11ea-8e31-8036939f5394.jpg)

**Comment by Lukazovic** [comment]
You can hide the scroll bar by adding `overflow: hidden`. I have added it in the index.css so it will be applied to the whole app.

index.js:
`body{
  overflow: hidden;
}`

I know it may be kind of late but better late than never 😅
